config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  resources :products
  get 'page/about'
  get 'page/faqs'
  get 'page/contact'
  root 'page#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

before_action :authenticate_user!, except: [:index]

  def add
    id = params[:id]
    # if hte cart has already been created, use the existing cart else create a new cart.
      if session[:cart]
        cart = session[:cart]
      else
        session[:cart] = {}
        cart = session[:cart]
      end
      # if the product has already been added to the cart, increment the value else set the value to 1.
      if cart[id] then
        cart[id] = cart[id] + 1
      else
        cart[id] = 1
      end
    redirect_to :action => :index
  end



  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
  end


  def index
    # if there is a cart, pass it to the page for display else pass an empty value.
    if session[:cart]
      @cart = session[:cart]
    else
      @cart = {}
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!, only: [:contact]

  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category, :subcategory)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1>Your cart</h1>

<% if @cart.empty? %>
  <p>Your cart is currently empty</p>
<% else %>
  <%= link_to 'Empty your cart', cart_clear_path %>
<% end %>
<br><br><br><br>

<% total = 0 %>

<ul>
<%  @cart.each do | id, quantity | %>
  <% product = Product.find_by_id(id) %>

  <li>
    <%= link_to product.title, product %>
    <p><%= product.description %></p>
    <p><%= number_to_currency(product.price, :unit => '$') %></p>
    <p>Quantity: <%= quantity %></p>
  </li>
  <% total += quantity * product.price  %>
<% end %>

<br><br><br>
<p>Total: </p>
<p><b><%= number_to_currency(total, :unit => '$') %></b></p>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CartApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="nav">
  <div id="page_nav">
    <%= link_to 'Home', root_path %>
    <%= link_to 'Shop', products_path %>
    <%= link_to 'About', page_about_path %>
    <%= link_to 'FAQs', page_faqs_path %>
    <%= link_to 'Contact', page_contact_path %>
  </div>
  <div id="sign_in">
    <% if user_signed_in? %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign In',new_user_session_path %>
      <%= link_to 'Sign Up', new_user_registration_path %>
    <% end -%>
  </div>
</nav>
<div id="main_wrap">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/faqs.html.erb
<h1>Page#faqs</h1>
<p>Find me in app/views/page/faqs.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br>
    <%= f.text_field :subcategory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.price %></td>
        <td><%= product.category %></td>
        <td><%= product.subcategory %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><a href="/cart/<%= product.id %>">Add To Cart</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @product.subcategory %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>